---
title: "Modeling_Project"
author: "Miu Radu, ANY Gohou, SINGH Shalini, PHUNG Ngoc Uyen"
date: "2023-11-11"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Import lybraries for R and Python

```{r}
library(readxl)
library(reticulate)
```

```{python}
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
```

```{python}
# Load the Data Frame
unicorn_data = pd.read_excel('CB-Insights_Global-Unicorn-Club_2023.xlsx')
```

```{python}
# Cleaning the data
## Removing useless columns
unicorn_data = unicorn_data.dropna(subset="Valuation ($B)")

## Dealing with missing value in "Country"
unicorn_data.loc[537, "Country"] = "Singapour"

## Removing ",," in "Select investors" corectly count  number of investors
unicorn_data ["Select Investors"] = unicorn_data ["Select Investors"].str.replace(",,",",")

# Counting the number of Investors
unicorn_data["Number_of_Investors"] = unicorn_data["Select Investors"].str.split(",", expand=False).str.len()

investors = unicorn_data["Select Investors"].str.split(",", expand=True)

unicorn_data_cleaned = unicorn_data.join(investors)

unicorn_data_cleaned = unicorn_data_cleaned.rename(columns={0: "1st_investor", 1: "2nd_investor", 2: "3td_investor", 3: "4td_investor"})

unicorn_data_cleaned.info()

```

```{python}
fig, ax = plt.subplots()
sns.countplot(
  data=unicorn_data_cleaned,
  x="Industry",
  stat='count',
  ax=ax
  ).set(title="Distribution of the number of companies per Industry")
plt.setp(ax.get_xticklabels(), rotation=45, ha="right",
         rotation_mode="anchor")
plt.tight_layout()
plt.show()

```



```{python}
unicorn_data_cleaned.value_counts("Country")
```

```{python}
sns.displot(
  data=unicorn_data_cleaned,
  x="Number_of_Investors",
  kind="hist", 
  hue="Industry", 
  multiple="dodge"
  )
plt.title("Distribution of the number of investors per Industry")
plt.show()
```

```{python}
sns.displot(
  data=unicorn_data_cleaned,
  x="Number_of_Investors",
  kind="kde",
  fill=True
  )
plt.title("Distribution of the number of investors")
plt.show()
```

```{r}
py$unicorn_data_cleaned

py$investors
```

```{r}
library(ggplot2)

# Plotting the distribution of the number of companies per Industry
ggplot(py$unicorn_data_cleaned, aes(x = Industry)) +
  geom_bar(stat = "count") +
  labs(title = "Distribution of the number of companies per Industry")
```

