---
title: "Modeling_Project"
author: "Miu Radu, ANY Gohou, SINGH Shalini, PHUNG Ngoc Uyen"
date: "2023-11-11"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Import lybraries for R and Python

```{r}
library(readxl)
library(reticulate)
library(ggplot2)

```

```{python}
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
from datetime import date
```

```{python}
# Load the Data Frame
unicorn_data = pd.read_excel('CB-Insights_Global-Unicorn-Club_2023.xlsx')
```

```{python}
# Cleaning the data
today = date.today()

## Removing useless columns
unicorn_data = unicorn_data.dropna(subset="Valuation ($B)")

## Dealing with missing value in "Country"
unicorn_data.loc[537, "Country"] = "Singapour"

## Removing ",," in "Select investors" corectly count  number of investors
unicorn_data ["Select Investors"] = unicorn_data ["Select Investors"].str.replace(",,",",")

## Counting the number of Investors
unicorn_data["Number_of_Investors"] = unicorn_data["Select Investors"].str.split(",", expand=False).str.len()

## Adding all the investors in a different column + renaming the columns
investors = unicorn_data["Select Investors"].str.split(",", expand=True)
unicorn_data_cleaned = unicorn_data.join(investors)
unicorn_data_cleaned = unicorn_data_cleaned.rename(columns={0: "1st_investor", 1: "2nd_investor", 2: "3td_investor", 3: "4td_investor"})

unicorn_data_cleaned.info()

(pd.Timestamp.today() - unicorn_data_cleaned["Date Joined"]) / np.timedelta64(1,'Y')

```

```{r}
#| fig.width: 10
#| fig.height: 6.4

# Plotting the distribution of the number of companies per Industry
ggplot(py$unicorn_data_cleaned, aes(x = Industry, color = Industry, fill = Industry)) +
  geom_bar(stat = "count") +
  labs(title = "Distribution of the number of companies per Industry")+
  theme(axis.text.x = element_text(angle = 45, hjust=1))

```


```{r}
ggplot(py$unicorn_data_cleaned, aes(x = Number_of_Investors, fill = Industry))+
  geom_histogram(position = "dodge", bins = 30, alpha = 0.7) +
  ggtitle("Distribution of the number of investors per Industry") 
  
```

```{r}
ggplot(py$unicorn_data_cleaned, aes(x = Number_of_Investors )) +
  geom_density(alpha = 0.7) +
  ggtitle("Distribution of the number of investors") +
  scale_fill_viridis_c()
```

```{r}
py$unicorn_data_cleaned

py$investors
```

