---
title: "Report_to_submit_R"
author: "Ngoc Uyen PHUNG"
date: "2023-11-27"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE}
# Load the package
library(tidyverse)

library(readxl)
library(countrycode)
library(magrittr) # to use the pipe

# Visualization
library(hrbrthemes) # different themes for ggplot2 
library(paletteer)
library(plotly) # to have dynamic plot
```

```{r}
names_sort_count = function(data, decreasing=TRUE){
  return(
  data %>% 
    table() %>% 
    sort(decreasing = decreasing) %>% 
    names()
  )
}

cors <- function(df, type="pearson") { 
  # turn all three matrices (r, n, and P into a data frame)
  M <- Hmisc::rcorr(as.matrix(df), type = type)
  # return the three data frames in a list return(Mdf)
  Mdf <- map(M, ~data.frame(.x))
  return(Mdf)
}

formatted_cors <- function(df, type="pearson"){
  cors(df, type) %>%
    map(~rownames_to_column(.x, var="measure1")) %>%
    # format each data set (r,P,n) long
    map(~pivot_longer(.x, cols = -measure1, names_to = "measure2")) %>%
    # merge our three list elements by binding the rows
    bind_rows(.id = "id") %>%
    pivot_wider(names_from = id, values_from = value) %>%
    mutate(sig_p = ifelse(P < .05, T, F), p_if_sig = ifelse(P <.05, P, NA), r_if_sig = ifelse(P <.05, r, NA)) 
}
```

```{r}
# Load the data
unicorn_data <- read_excel("../DataSets/CB-Insights_Global-Unicorn-Club_2023.xlsx")
```

## Cleaning the data

```{r pressure}
# Renaming Columns
colnames(unicorn_data) <- c('company','valuation_billions','date_added','country','city','industry','select_investors')

# Removing the duplicate company 
unicorn_data = unicorn_data %>% 
  distinct( .keep_all = T)

# Removing useless columns
unicorn_data = drop_na(unicorn_data, valuation_billions)


#Sequoia Capital firm name to avoid error when creating new df "unicorn_investors"
unicorn_data$select_investors <- gsub("and Sequoia Capital China", "Sequoia Capital China", unicorn_data$select_investors)


# Dealing with missing value in "country"
unicorn_data[538, "country"] <- "Singapore"

# Remove "City" column
unicorn_data <- subset(unicorn_data, select = -city)

# Removing ",," in "Select investors" correctly count  number of investors
unicorn_data$select_investors <- gsub(",,", ",", unicorn_data$select_investors)

# Counting the number of Investors
unicorn_data$Number_of_Investors <- sapply(strsplit(as.character(unicorn_data$select_investors), ","), length)

# Replacing City names in the country variable
unicorn_data$country <- gsub("London", "United Kingdom", unicorn_data$country)
unicorn_data$country <- gsub("Munchen", "Germany", unicorn_data$country)

# continent Values
unicorn_data$continent = countrycode(sourcevar = unicorn_data$country,
                            origin = "country.name",
                            destination = "continent")

# Year Conversion 
unicorn_data$date_added = ymd(unicorn_data$date_added)

# Years since Joined
unicorn_data$age = interval(unicorn_data$date_added, now()) %/% years(1)

# Add column year
unicorn_data$year_added <- year(unicorn_data$date_added)

unicorn_data <- unicorn_data %>%
  mutate(target = 
           ifelse(valuation_billions >= 5, "Over 5 $B",  "Under 5 $B") %>% as.factor()) %>% 
  mutate(target_code = as.numeric(target) ) %>% 
  # Making Sure each company name is well differentiated from one another
  mutate(company = paste(row.names(unicorn_data), unicorn_data$company))
  
unicorn_data$industry = factor(unicorn_data$industry)
unicorn_data$continent = factor(unicorn_data$continent)
unicorn_data$country = factor(unicorn_data$country)
```
## Transform the Data

```{r}
# Creating an intermediary dataframe for later computations
unicorn_transition <- unicorn_data %>%
  mutate(select_investors = strsplit(select_investors, ",")) %>% 
  unnest(select_investors) %>% 
  mutate(select_investors = str_trim(select_investors)) 

# Creating the investors oriented dataframe for further analysis
unicorn_investors = unicorn_transition %>% 
  summarise(.by = select_investors,
            investements_count=n(),
            investements=list(company), 
            investements_sum_valuation=sum(valuation_billions),
            investements_mean_valuation=mean(valuation_billions), 
            investements_over5B_count=sum(target_code), 
            investements_over5B_pct=investements_over5B_count/investements_count
            )

# Investor average percentage over 5B
associate_investor = unicorn_investors %>% 
  unnest(investements) %>% 
  summarise(.by = investements, 
            investements_avg_pct_over5B = mean(investements_over5B_pct)
            )


# Creating the associate companies trasition dataframe for later compuations 
associate_transition = unicorn_transition %>% 
  # Having two columns containing all the companies per Investor in a list
    summarise(.by = select_investors,
            associated_companies=list(company), 
            company=list(company)
            ) %>%
  # For each company we have their investors and a list of the companies 
  # the investors invested in. 
  unnest(company) %>% 
  # Unnesting the second column containg all the companies resulting in the 
  #duplication of all the other columns
  unnest(associated_companies) %>% 
  # Deleting the company name from the associated_company list
  # For each company, we will delete all the duplicates in the association company
  summarise(.by=company,
            associated_companies = unique(associated_companies)
            )

# Creating associate companies data frame with info regarding the associated companies

associate_companies = associate_transition %>% 
  # Deleting the company name from the associated_company list
  subset(company!=associated_companies) %>% 
  left_join(unicorn_data, by=join_by(associated_companies == company)) %>% 
  summarise(.by=company,
            associated_companies = list(unique(associated_companies)), 
            associated_count= n(),
            associated_count_over5Bill=sum(target_code), 
            associated_pct_over5Bill=associated_count_over5Bill/associated_count
            )

# Creating the associate valuation data frame with info regarding associate company valuation 
associate_valuation = associate_transition %>% 
  left_join(unicorn_data, by=join_by(associated_companies == company)) %>% 
  summarise(.by = company,
            association_total_value = sum(valuation_billions), 
            association_mean_value = mean(valuation_billions)
            )

unicorn_data_complete = unicorn_data %>% 
  left_join(associate_companies, by="company") %>% 
  left_join(associate_valuation, by="company") %>% 
  left_join(associate_investor, by=join_by(company == investements))

unicorn_data_complete = unicorn_data_complete %>% 
  mutate(associated_count = ifelse(
    is.na(associated_count), 
    0, 
    associated_count
    )
  ) %>% 
  mutate(associated_count_over5Bill = ifelse(
    is.na(associated_count_over5Bill), 
    0, 
    associated_count_over5Bill
    )
  ) %>% 
    mutate(associated_pct_over5Bill = ifelse(
    is.na(associated_pct_over5Bill), 
    0, 
    associated_pct_over5Bill
    )
  )
```

## Trim the Data 

```{r}
unicorn_data_trimmed = unicorn_data_complete %>% 
  select(-c(date_added, select_investors, associated_companies, valuation_billions)) %>% 
  mutate(country_code = as.numeric(country)) %>% 
  mutate(industry_code = as.numeric(industry)) %>%
  mutate(continent_code = as.numeric(continent))

unicorn_data_trimmed %>% 
  summary()
  
unicorns_corelation= unicorn_data_trimmed %>% 
  select(-c(company, country, industry, target, continent, associated_count_over5Bill, associated_count, year_added))
```

```{r, fig.height=6.4, fig.width=8}
formatted_cors(unicorns_corelation) %>% 
  ggplot(aes(measure1, measure2, fill=r, label=round(r_if_sig,2))) +
  geom_tile() +
  labs(x = NULL, y = NULL, fill = "Pearson's\nCorrelation", title="Correlations in Unicorn_Corelation", subtitle="Only significant Pearson's correlation coefficients shown") +
  scale_fill_gradient2(mid="#FBFEF9",low="#0C6291",high="#A63446", limits=c(-1,1)) +
  geom_text() +
  theme_classic() +
  scale_x_discrete(expand=c(0,0)) +
  scale_y_discrete(expand=c(0,0)) +
  theme(axis.text.x = element_text(angle = 45, hjust=1))
```

```{r, fig.height=6.4, fig.width=8}
formatted_cors(unicorns_corelation, "spearman") %>% 
  ggplot(aes(measure1, measure2, fill=r, label=round(r_if_sig,2))) +
  geom_tile() +
  labs(x = NULL, y = NULL, fill = "Spearman's\nCorrelation", title="Correlations in Unicorn_Corelation", subtitle="Only significant Pearson's correlation coefficients shown") +
  scale_fill_gradient2(mid="#FBFEF9",low="#0C6291",high="#A63446", limits=c(-1,1)) +
  geom_text() +
  theme_classic() +
  scale_x_discrete(expand=c(0,0)) +
  scale_y_discrete(expand=c(0,0)) +
  theme(axis.text.x = element_text(angle = 45, hjust=1))
```


```{r}

ggplot(unicorn_data, aes(x = industry)) +
  geom_bar(stat = "count", fill = "steelblue") +
  labs(title = "Distribution of the number of companies per industry") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  xlim(names_sort_count(unicorn_data$industry))

```

```{r}
ggplot(unicorn_data, aes(x = country)) +
  geom_bar(stat = "count", fill = "steelblue") +
  xlim(names_sort_count(unicorn_data$country))+
  labs(title = "Distribution of the number of companies per country") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
ggplot(unicorn_data, aes(x = continent)) +
  geom_bar(stat = "count", fill = "steelblue") +
  xlim(names_sort_count(unicorn_data$continent))+
  labs(title = "Distribution of the number of companies per country") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
ggplot(unicorn_data, aes(x = Number_of_Investors, fill = industry)) +
  geom_bar(stat = "count", position = "dodge") +
  labs(title = "Distribution of the number of investors")+
  scale_fill_paletteer_d("awtools::a_palette")
```

```{r pressure, echo=FALSE}
table1 <- table(unicorn_data$country, unicorn_data$target)
chiSqResult <- chisq.test(table1)
print(chiSqResult)


table2 <- table(unicorn_data$industry, unicorn_data$target)
chiSqResult <- chisq.test(table2)
print(chiSqResult)


table3 <- table(unicorn_data$continent, unicorn_data$target)
chiSqResult <- chisq.test(table3)
print(chiSqResult)


table4 <- table(unicorn_data$Number_of_Investors, unicorn_data$target)
chiSqResult <- chisq.test(table4)
print(chiSqResult)


table5 <- table(unicorn_data$Year_Joined, unicorn_data$target)
chiSqResult <- chisq.test(table5)
print(chiSqResult)


table6 <- table(unicorn_data$Age, unicorn_data$target)
chiSqResult <- chisq.test(table6)
print(chiSqResult)


```

------------------------ Explanatory variables as factor 
## Link between variables

```{r}
unicorn_data_complete$country<-factor(unicorn_data_complete$country)
unicorn_data_complete$industry<-factor(unicorn_data_complete$industry)
unicorn_data_complete$continent<-factor(unicorn_data_complete$continent)
unicorn_data_complete$Number_of_Investors<-factor(unicorn_data_complete$Number_of_Investors)
unicorn_data_complete$year_added<-factor(unicorn_data_complete$year_added)
unicorn_data_complete$age<-factor(unicorn_data_complete$age)
unicorn_data_complete$associated_count<-factor(unicorn_data_complete$associated_count)
unicorn_data_complete$associated_count_over5Bill<-factor(unicorn_data_complete$associated_count_over5Bill)
unicorn_data_complete$associated_pct_over5Bill<-factor(unicorn_data_complete$associated_pct_over5Bill)
unicorn_data_complete$association_total_value<-factor(unicorn_data_complete$association_total_value)
unicorn_data_complete$association_mean_value<-factor(unicorn_data_complete$association_mean_value)
unicorn_data_complete$investements_avg_pct_over5B<-factor(unicorn_data_complete$investements_avg_pct_over5B)
```

Now that all our variables are categorical, we have 2 possible tests to compute. Both having the same hypotesis.
H0: No link
H1: Existing link

```{r pressure, echo=FALSE}
table1 <- table(unicorn_data_complete$country, unicorn_data_complete$target)
chiSqResult <- chisq.test(table1)
print(chiSqResult)


table2 <- table(unicorn_data_complete$industry, unicorn_data_complete$target)
chiSqResult <- chisq.test(table2)
print(chiSqResult)


table3 <- table(unicorn_data_complete$continent, unicorn_data_complete$target)
chiSqResult <- chisq.test(table3)
print(chiSqResult)


table4 <- table(unicorn_data_complete$Number_of_Investors, unicorn_data_complete$target)
chiSqResult <- chisq.test(table4)
print(chiSqResult)


table5 <- table(unicorn_data_complete$year_added, unicorn_data_complete$target)
chiSqResult <- chisq.test(table5)
print(chiSqResult)


table6 <- table(unicorn_data_complete$age, unicorn_data_complete$target)
chiSqResult <- chisq.test(table6)
print(chiSqResult)

table7 <- table(unicorn_data_complete$associated_count, unicorn_data_complete$target)
chiSqResult <- chisq.test(table7)
print(chiSqResult)

table8 <- table(unicorn_data_complete$associated_count_over5Bill, unicorn_data_complete$target)
chiSqResult <- chisq.test(table8)
print(chiSqResult)

table9 <- table(unicorn_data_complete$associated_pct_over5Bill, unicorn_data_complete$target)
chiSqResult <- chisq.test(table9)
print(chiSqResult)

table10 <- table(unicorn_data_complete$association_total_value, unicorn_data_complete$target)
chiSqResult <- chisq.test(table10)
print(chiSqResult)

table11 <- table(unicorn_data_complete$association_mean_value, unicorn_data_complete$target)
chiSqResult <- chisq.test(table11)
print(chiSqResult)

table12 <- table(unicorn_data_complete$investements_avg_pct_over5B, unicorn_data_complete$target)
chiSqResult <- chisq.test(table12)
print(chiSqResult)


```

## KHI2 test with "coin"
```{r}
#install.packages("coin")
library(coin)

CoinResult1 <- chisq_test(table1)
print(CoinResult1)

CoinResult2 <- chisq.test(table2)
print(CoinResult2)

CoinResult3 <- chisq.test(table3)
print(CoinResult3)

CoinResult4 <- chisq.test(table4)
print(CoinResult4)

CoinResult5 <- chisq.test(table5)
print(CoinResult5)

CoinResult6 <- chisq.test(table6)
print(CoinResult6)

CoinResult7 <- chisq.test(table7)
print(CoinResult7)

CoinResult8 <- chisq.test(table8)
print(CoinResult8)

CoinResult9 <- chisq.test(table9)
print(CoinResult9)

CoinResult10 <- chisq.test(table10)
print(CoinResult10)

CoinResult11 <- chisq.test(table11)
print(CoinResult11)

CoinResult12 <- chisq.test(table12)
print(CoinResult12)
```

```{r}
print(table1)
print(table2)
print(table3)
print(table4)
print(table5)
print(table6)
print(table7)
print(table8)
print(table9)
print(table10)
print(table11)
print(table12)
```

So we will try the Fisher test :

```{r}
FisherResult1 <- fisher.test(table1, simulate.p.value = TRUE)
print(FisherResult1)

FisherResult2 <- fisher.test(table2, simulate.p.value = TRUE)
print(FisherResult2)

FisherResult3 <- fisher.test(table3, simulate.p.value = TRUE)
print(FisherResult3)

FisherResult4 <- fisher.test(table4, simulate.p.value = TRUE)
print(FisherResult4)

FisherResult5 <- fisher.test(table5, simulate.p.value = TRUE)
print(FisherResult5)

FisherResult6 <- fisher.test(table6, simulate.p.value = TRUE)
print(FisherResult6)

FisherResult7 <- fisher.test(table7, simulate.p.value = TRUE)
print(FisherResult7)

FisherResult8 <- fisher.test(table8, simulate.p.value = TRUE)
print(FisherResult8)

FisherResult9 <- fisher.test(table9, simulate.p.value = TRUE)
print(FisherResult9)

FisherResult10 <- fisher.test(table10, simulate.p.value = TRUE)
print(FisherResult10)

FisherResult11 <- fisher.test(table11, simulate.p.value = TRUE)
print(FisherResult11)

FisherResult12 <- fisher.test(table12, simulate.p.value = TRUE)
print(FisherResult12)
```
## Model Building 

# Dataset splitting
```{r}
# Training set and test set
set.seed(100)
row.number <- sample(1:nrow(unicorn_data_complete), 0.8*nrow(unicorn_data_complete))
train=unicorn_data_complete[row.number,]
test=unicorn_data_complete[-row.number,]

# Splitting efficiency check 

prop.table(table(unicorn_data_complete$target))
prop.table(table(train$target))
prop.table(table(test$target))

```
Overall we have a higher proportion of Under 5 $B, that evenly distributed in each sets.

#Logistic Regression

#Train
```{r}
logit_model <- glm (target ~year_added + age + Number_of_Investors + 
    associated_count + associated_count_over5Bill + associated_pct_over5Bill + 
    association_total_value + association_mean_value + investements_avg_pct_over5B, 
                      data=train,binomial(link="logit"))
summary(logit_model)
```
## Performance evaluation 
```{r}
library(gmodels) 
logit_prediction_test <- predict(logit_model, newdata = test, type = "response")

prop.table(table(logit_prediction_test >0.5,test$target))

CrossTable(logit_prediction_test>0.5,test$target, prop.chisq=FALSE,
chisq=FALSE,prop.t=FALSE,dnn = c("Predicted","Actual"))
```

-----------------------------Decision Tree------------------------------
```{r}
library(rpart)
library(rpart.plot)
```

Train Decision Tree model
```{r}
decision_tree <- rpart(target~year_added + age + Number_of_Investors + associated_count + associated_count_over5Bill + associated_pct_over5Bill + association_total_value + association_mean_value + investements_avg_pct_over5B,
method="class", data=train,
control=rpart.control(minsplit=1),
parms=list(split="information"))

summary(decision_tree)
```

Plot the decision tree
```{r}
rpart.plot(decision_tree, type=2, extra=1)
```

```{r}
tree_prediction_test <- predict(decision_tree,newdata=test,type="class")
```

```{r}
# Confusion matrix for decision tree
confusion_tree <- table(tree_prediction_test, test$target)

# Display confusion matrix
print(confusion_tree)

# Calculate accuracy for decision tree
accuracy_tree <- sum(diag(confusion_tree))/sum(confusion_tree)
print(paste("Accuracy for Decision Tree:", accuracy_tree))

# CrossTable function for a more detailed analysis
CrossTable(tree_prediction_test, test$target, prop.chisq=FALSE,
           chisq=FALSE, prop.t=FALSE, dnn = c("Predicted", "Actual"))
```


